### ISSUE TITLE
403 error on first OAUTH reddit request via mobile

### ISSUE THREAD

**Issue by Ethicmeta** [Heep123/SubredditPoints#12]
Message reads Invalid state parameter returned on first request. Attempting to log in again and accepting through reddit resolves the second time. I am able to consistently recreate this issue.

**Comment by Glyciant** [comment]
I've had a few attempts to try and replicate this, but all authentication attempts worked out.

It is usually caused when your browser clears your session mid-authentication. But... that wouldn't really explain why suddenly works the second time.

Given the fact that this is only on mobile, and nobody else has reported this, I'm going to draw the conclusion it seems to be on your side unfortunately 😕
