### ISSUE TITLE
[Suggestion] Group similar transactions, one update date field, one total field

### ISSUE THREAD

**Issue by Ethicmeta** [Heep123/SubredditPoints#2]
The list can become insanely long and essentially useless when you regularly stream to the twitch community. Grouping by transaction type, updating date field to latest date and totaling the amount per transaction type would go a long way to a better UX.

**Comment by Glyciant** [comment]
I'll see what I can do 🙂

**Comment by Glyciant** [comment]
This should now be a thing... I hope so anyway. Let me know if there's anything further!
