### ISSUE TITLE
Every login requires reddit auth

### ISSUE THREAD

**Issue by Ethicmeta** [Heep123/SubredditPoints#3]
```
Allow Subreddit Points to:
Access my reddit username and signup date.
Maintain this access indefinitely (or until manually revoked).
Subreddit Points will not be able to access your reddit password.
```

On every logon. Appears its requesting a new oath token. Are you storing it?

**Comment by Glyciant** [comment]
Unlike with Twitch's API, you are required to click "Allow" on Reddit every time. The token is stored in the session variables, but that's it. I don't use cookies or anything on TwitchDB. Is this posing an issue, or it is just more of an annoyance?

**Comment by Ethicmeta** [comment]
Annoyance, general UX stuff. It's not really an issue as once you set it up there isn't much of a reason to revisit the site.

**Comment by Glyciant** [comment]
Going to mark this as a won't fix then.
