### ISSUE TITLE
[suggestion] more changes to the transactions tab

### ISSUE THREAD

**Issue by Ethicmeta** [Heep123/SubredditPoints#4]
Users dont need to see the transaction ID or from fields. The header field for what I think is suppose to be Total is titled 'Difference'. Can you clarify? Also, what is description field going to be used for? every entry I've seen has been '-'

The grouping doesn't appear to function, either. I have two entries for 5/21/17 for streaming to the community, .25 and .5, an entry for 5/20 for 30 points.

**Comment by Glyciant** [comment]
Transaction ID is there in case a user needs to modmail us about a particular transaction they need help with. We have a mod tool for looking up further information about each transaction.

Difference is how many Twoos have been added/removed by that transaction. So 15 minutes of streaming is +0.25. Nominations are +1, etc.

Description is used for nominations mainly. So it will link the particular comment in this instance. Though I suppose the new grouping sort of makes this redundant.

I'm assuming there is something between the 20/5/17 and 21/5/17 transactions, in which case it is working as intended. The thing with 0.25 and 0.5 being separate is a bit odd though. I'll have to look into it further.

**Comment by Ethicmeta** [comment]
Wouldnt the transaction ID also be redundant with the new grouping setup? This might over complicate things, but having an admin view of users with each of their individual transactions listed as they were before the grouping was applied may prove useful for admins while keeping the user's experience clean

**Comment by Glyciant** [comment]
Yeah, that's true about it being redundant. 

I've eaten a sandwich and thought about this issue a little more. I will change it around a little bit so it displays the group as a "header" of sorts. Clicking this header will expand an indented list of all the transactions within it, including the ID. 

Hopefully this should make it tidier, but also allows all information to be accessed. 

Thanks for the help on this, I'll relabel it now 🙂

**Comment by Glyciant** [comment]
The columns are all over the place now. Needs fixing.
